server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/post2501
    username: ${LOCAL_USERNAME}
    password: ${LOCAL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
